name: Telegram Mafia Bot - Auto Restart on Push

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/**'

permissions:
  contents: read
  actions: write

jobs:
  restart-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from secret
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

      - name: Stop existing bot
        run: |
          echo "Stopping existing bot processes..."
          pkill -f "python main.py" || true
          sleep 5

      - name: Start bot with latest code
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Starting bot with latest code..."
          nohup python main.py > bot.log 2>&1 &
          BOT_PID=$!
          
          # Ждем для проверки запуска
          sleep 10
          
          # Проверяем, что бот запустился
          if ps -p $BOT_PID > /dev/null; then
            echo "Bot restarted successfully with PID: $BOT_PID"
            echo "Bot log:"
            tail -20 bot.log
          else
            echo "Failed to restart bot"
            echo "Bot log:"
            cat bot.log
            exit 1
          fi

      - name: Trigger main workflow for monitoring
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Triggering main workflow for 6-hour monitoring..."
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yml/dispatches \
            -d '{"ref":"main"}'
          
          echo "Main workflow triggered successfully"


