name: Telegram Mafia Bot

on:
  workflow_dispatch:
  schedule:
    # Перезапуск каждые 6 часов
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 часов максимум
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot for 6 hours
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Starting bot for 6 hours..."
          python main.py &
          BOT_PID=$!
          
          # Ждем 6 часов (21600 секунд)
          sleep 21600
          
          # Останавливаем бота
          kill $BOT_PID 2>/dev/null || true
          echo "Bot stopped after 6 hours"

      - name: Restart bot immediately
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Restarting bot..."
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yml/dispatches \
            -d '{"ref":"main"}'
          echo "Bot restarted"

